baseurl = "/"
title = "IX Stockholm"
theme = "hyde-x"
paginate = 10
DefaultContentLanguage = "sv"

[taxonomies]
  category = "categories"
  author = "authors"

[params]
  logoPath = "/img/logo/ix-drone-logo-white.svg"
  github = "https://github.com/ix-sthlm/"
  meetup = "https://meetup.com/IX-Stockholm"
  rss = true
  sidebar_license_page = false

[languages]
  [languages.sv]
    languageCode = "sv-se"

    [languages.sv.permalinks]
      post = "/blog/:year/:month/:day/:title/"

    [languages.sv.params]
      home = "Blogg"

    [[languages.sv.menu.main]]
      name = "Projekt"
      url = "/projects/"

    [[languages.sv.menu.main]]
      name = "Om oss"
      url = "/about/"

    [[languages.sv.menu.main]]
      name = "Integritetspolicy"
      url = "/about_privacy/"

    [[languages.sv.menu.main]]
      name = "Kalender"
      url = "/calendar/"

    [[languages.sv.menu.main]]
      name = "Bli medlem"
      url = "/membership/"

  [languages.en]
    languageCode = "en-us"

    [languages.en.params]
      home = "Swedish site"

    [[languages.en.menu.main]]
      name = "About us"
      url = "/en/about/"
